version: '2'

networks:
  prodnetwork:
    driver: bridge

services:

  nexus:
    image: sonatype/nexus3:3.6.1
    ports:
      - "18081:8081"
    networks:
      - prodnetwork

  jenkins:
    build: ./jenkins
    ports:
      - "18080:8080"
    depends_on:
      - nexus
      - gitlab
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /opt/jenkins/:/var/lib/jenkins/
    networks:
      - prodnetwork

  sonar:
    build: ./sonar
    ports:
      - "19000:9000"
      - "5432:5432"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - prodnetwork
    depends_on:
      - sonardb

  sonardb:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /var/lib/postgresql/data
    networks:
      - prodnetwork

  gitlab:
    image: gitlab/gitlab-ce:10.2.1-ce.0
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    networks:
      - prodnetwork
